name: Verify Pull Request

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x.x

      - name: Restore dependencies
        run: dotnet restore /Src/Service/Api/Api.csproj

      - name: Build
        run: dotnet build /Src/Service/Api/Api.csproj --no-restore --configuration Release
