name: Verify Pull Request

on:
  push:

env:
  PROJECT_PATH: src/Service/Api/Api.csproj

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore src/Service/Api/Api.csproj

      - name: Build
        run: dotnet build $PROJECT_PATH --no-restore --configuration Release

      - name: Test
        run: dotnet test $PROJECT_PATH --no-build --configuration Release
      
      - name: Publish
        run: dotnet publish --no-restore --configuration Release --output ./output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: my-artifact
         path: output/
  
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
         name: my-artifact
         path: ./download/
     
      - name: Display structure of downloaded files
        run: ls -R ./download/
      