name: Verify Pull Request

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore RoyStore.sln

      - name: Build
        run: dotnet build RoyStore.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test RoyStore.sln --no-build --configuration Release
